spring.application.name=TP_backend

#port ?? ??
server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3307/bookclub_db
spring.datasource.username=bookclub
spring.datasource.password=bookclub
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

debug=true

jwt.secret=mysecretkey_teamproject02
